# Generated by Django 2.0.5 on 2018-07-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20180701_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='groupteam',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupteam',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Team'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupTeam',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
