# Generated by Django 2.0.5 on 2018-07-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20180705_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team')),
            ],
        ),
    ]
