# Generated by Django 2.0.5 on 2018-07-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20180706_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('team', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='resign',
            unique_together={('team', 'profile')},
        ),
    ]
