# Generated by Django 2.0.5 on 2018-07-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20180707_0850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamcontest',
            unique_together={('team', 'contest')},
        ),
    ]
