# Generated by Django 2.0.5 on 2018-07-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_matchteam_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchteam',
            unique_together={('team', 'match')},
        ),
    ]
