# Generated by Django 2.0.5 on 2018-07-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20180714_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(blank=True, through='contest.MatchTeam', to='contest.Team'),
        ),
    ]
