# Generated by Django 2.0.5 on 2018-07-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20180719_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(through='contest.MatchTeam', to='contest.Team'),
        ),
    ]
