# Generated by Django 2.0.5 on 2018-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20180719_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='required_matches',
            field=models.ManyToManyField(related_name='_match_required_matches_+', to='contest.Match'),
        ),
    ]
